### ISSUE TITLE
undefined symbol: _ZN3c1017RegisterOperatorsC1Ev

### ISSUE THREAD

**Issue by sorenwacker** [j9650/MedusaGraph#3]
I am executing the example command from the README file:

```
python medusagraph.py --ligand_file=data/pdbbind/1nja/1nja.lig.mol2 --protein_file=data/pdbbind/1nja/1nja.rec.pdb --pose_file=data/medusadock_output/1nja.pdb --output_file=MedusaGraph_tmp/1nja.mol2 --prediction_model=models/prediction_model.pt --selection_model=models/selection_model.pt --tmp_dir=MedusaGraph_tmp/
```

Which returns this error:
```
Traceback (most recent call last):
  File "medusagraph.py", line 8, in <module>
    from torch_geometric.data import DataLoader
  File "/home/swacker/miniconda3/envs/torch/lib/python3.8/site-packages/torch_geometric/__init__.py", line 4, in <module>
    import torch_geometric.data
  File "/home/swacker/miniconda3/envs/torch/lib/python3.8/site-packages/torch_geometric/data/__init__.py", line 1, in <module>
    from .data import Data
  File "/home/swacker/miniconda3/envs/torch/lib/python3.8/site-packages/torch_geometric/data/data.py", line 9, in <module>
    from torch_sparse import SparseTensor
  File "/home/swacker/miniconda3/envs/torch/lib/python3.8/site-packages/torch_sparse/__init__.py", line 12, in <module>
    torch.ops.load_library(importlib.machinery.PathFinder().find_spec(
  File "/home/swacker/miniconda3/envs/torch/lib/python3.8/site-packages/torch/_ops.py", line 255, in load_library
    ctypes.CDLL(path)
  File "/home/swacker/miniconda3/envs/torch/lib/python3.8/ctypes/__init__.py", line 373, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: /home/swacker/miniconda3/envs/torch/lib/python3.8/site-packages/torch_sparse/_version.so: undefined symbol: _ZN3c1017RegisterOperatorsC1Ev
```

**Comment by sorenwacker** [comment]
Seems that is a CUDA problem...

**Comment by Fatima-Aslam** [comment]
Hi,
Same errors, I'm also facing. Can you please tell me How you resolve these?

Regards
Fatima

**Comment by Fatima-Aslam** [comment]
> I am executing the example command from the README file:
> 
> ```
> python medusagraph.py --ligand_file=data/pdbbind/1nja/1nja.lig.mol2 --protein_file=data/pdbbind/1nja/1nja.rec.pdb --pose_file=data/medusadock_output/1nja.pdb --output_file=MedusaGraph_tmp/1nja.mol2 --prediction_model=models/prediction_model.pt --selection_model=models/selection_model.pt --tmp_dir=MedusaGraph_tmp/
> ```
> 
> Which returns this error:
> 
> ```
> Traceback (most recent call last):
>   File "medusagraph.py", line 8, in <module>
>     from torch_geometric.data import DataLoader
>   File "/home/swacker/miniconda3/envs/torch/lib/python3.8/site-packages/torch_geometric/__init__.py", line 4, in <module>
>     import torch_geometric.data
>   File "/home/swacker/miniconda3/envs/torch/lib/python3.8/site-packages/torch_geometric/data/__init__.py", line 1, in <module>
>     from .data import Data
>   File "/home/swacker/miniconda3/envs/torch/lib/python3.8/site-packages/torch_geometric/data/data.py", line 9, in <module>
>     from torch_sparse import SparseTensor
>   File "/home/swacker/miniconda3/envs/torch/lib/python3.8/site-packages/torch_sparse/__init__.py", line 12, in <module>
>     torch.ops.load_library(importlib.machinery.PathFinder().find_spec(
>   File "/home/swacker/miniconda3/envs/torch/lib/python3.8/site-packages/torch/_ops.py", line 255, in load_library
>     ctypes.CDLL(path)
>   File "/home/swacker/miniconda3/envs/torch/lib/python3.8/ctypes/__init__.py", line 373, in __init__
>     self._handle = _dlopen(self._name, mode)
> OSError: /home/swacker/miniconda3/envs/torch/lib/python3.8/site-packages/torch_sparse/_version.so: undefined symbol: _ZN3c1017RegisterOperatorsC1Ev
> ```

Same errors, I'm also facing. Can you please tell me How to resolve these?
